// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB5pNeP4s5f3WF8Du6_oVTNce7vykswgc0",
    authDomain: "pawpoint-8822d.firebaseapp.com",
    projectId: "pawpoint-8822d",
    storageBucket: "pawpoint-8822d.firebasestorage.app",
    messagingSenderId: "325353125400",
    appId: "1:325353125400:web:ec39a0e67e20769d9a356d",
    measurementId: "G-P8Q6RE577H",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SoQ_wLenv19Fe8t2eqC8veaDQrBWpVI',
    appId: '1:64959176592:android:7793ded93cc31df6ae5d15',
    messagingSenderId: '64959176592',
    projectId: 'pawpoint-92f40',
    storageBucket: 'pawpoint-92f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdk-gJa9-kHl8gr3S_3Wd52yYvdhwWKvk',
    appId: '1:64959176592:ios:29a7f5c332692b69ae5d15',
    messagingSenderId: '64959176592',
    projectId: 'pawpoint-92f40',
    storageBucket: 'pawpoint-92f40.firebasestorage.app',
    iosBundleId: 'com.example.pawpointMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdk-gJa9-kHl8gr3S_3Wd52yYvdhwWKvk',
    appId: '1:64959176592:ios:29a7f5c332692b69ae5d15',
    messagingSenderId: '64959176592',
    projectId: 'pawpoint-92f40',
    storageBucket: 'pawpoint-92f40.firebasestorage.app',
    iosBundleId: 'com.example.pawpointMobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBwLYKwLlloQN5KVbGUkmwowtatLMDZdE',
    appId: '1:64959176592:web:abe4475523e7ff2dae5d15',
    messagingSenderId: '64959176592',
    projectId: 'pawpoint-92f40',
    authDomain: 'pawpoint-92f40.firebaseapp.com',
    storageBucket: 'pawpoint-92f40.firebasestorage.app',
    measurementId: 'G-VHYBQBYZ8V',
  );
}
